# Build Stage
FROM golang:1.25.0-alpine3.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/api

# Runtime stage
FROM alpine:3.22.1

WORKDIR /app

COPY --from=builder /app/server .

EXPOSE 8100

CMD ["./server"]
