name: CI-CD - Build Docker Images and Deploy to DockerHub

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    server-ci-check:
        name: Server CI Check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: '1.24.3'

            - name: Verify dependencies
              working-directory: ./server
              run: go mod verify

            - name: Run build
              working-directory: ./server
              run: go build -v ./...

            - name: Run go vet
              working-directory: ./server
              run: go vet ./...
    
    build-push-docker:
        name: Build and Push Docker Images
        needs: server-ci-check
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            
            # --- Server ---
            - name: Build and Push Server Image
              uses: docker/build-push-action@v6
              with:
                  context: ./server
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/my-ip-server:latest,${{ secrets.DOCKER_USERNAME }}/my-ip-server:1.1
                  file: ./server/Dockerfile
            
            # --- Client ---
            - name: Build and Push Client Image
              uses: docker/build-push-action@v6
              with:
                  context: ./client
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/my-ip-client:latest,${{ secrets.DOCKER_USERNAME }}/my-ip-client:1.1
                  file: ./client/Dockerfile

